CREATE DATABASE IF NOT EXISTS apdb;

-- Table: public.authentication
CREATE TABLE IF NOT EXISTS public.authentication
(
    id integer NOT NULL DEFAULT nextval('authentication_id_seq'::regclass),
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_sign_in_at timestamp with time zone,
    CONSTRAINT authentication_pkey PRIMARY KEY (id),
    CONSTRAINT authentication_username_key UNIQUE (username),
    CONSTRAINT authentication_username_key1 UNIQUE (username),
    CONSTRAINT authentication_username_key10 UNIQUE (username),
    CONSTRAINT authentication_username_key2 UNIQUE (username),
    CONSTRAINT authentication_username_key3 UNIQUE (username),
    CONSTRAINT authentication_username_key4 UNIQUE (username),
    CONSTRAINT authentication_username_key5 UNIQUE (username),
    CONSTRAINT authentication_username_key6 UNIQUE (username),
    CONSTRAINT authentication_username_key7 UNIQUE (username),
    CONSTRAINT authentication_username_key8 UNIQUE (username),
    CONSTRAINT authentication_username_key9 UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.authentication
    OWNER to postgres;


-- Table: public.farms
CREATE TABLE IF NOT EXISTS public.farms
(
    farm_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    crops text COLLATE pg_catalog."default",
    hectares bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    carbon_sequestered bigint,
    CONSTRAINT farms_pkey PRIMARY KEY (farm_id)
)

TABLESPACE pg_default;

-- Table: public.farmers
CREATE TABLE IF NOT EXISTS public.farmers
(
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    products text COLLATE pg_catalog."default",
    stock_level integer DEFAULT 0,
    status character varying(255) COLLATE pg_catalog."default",
    location character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    farmer_id integer NOT NULL DEFAULT nextval('farmers_farmer_id_seq'::regclass),
    CONSTRAINT farmers_status_check CHECK (status::text = ANY (ARRAY['Verified'::text, 'Unverified'::text]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.farmers
    OWNER to postgres;