CREATE DATABASE IF NOT EXISTS offline_sync_db;
USE offline_sync_db;

CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text TEXT NOT NULL,
  createdAtClient DATETIME NULL,
  clientLocalId INT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;