CREATE DATABASE IF NOT EXISTS apdb;

-- Table: public.authentication
CREATE TABLE IF NOT EXISTS public.authentication
(
    id integer NOT NULL DEFAULT nextval('authentication_id_seq'::regclass),
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_sign_in_at timestamp with time zone,
    CONSTRAINT authentication_pkey PRIMARY KEY (id),
    CONSTRAINT authentication_username_key UNIQUE (username),
    CONSTRAINT authentication_username_key1 UNIQUE (username),
    CONSTRAINT authentication_username_key10 UNIQUE (username),
    CONSTRAINT authentication_username_key2 UNIQUE (username),
    CONSTRAINT authentication_username_key3 UNIQUE (username),
    CONSTRAINT authentication_username_key4 UNIQUE (username),
    CONSTRAINT authentication_username_key5 UNIQUE (username),
    CONSTRAINT authentication_username_key6 UNIQUE (username),
    CONSTRAINT authentication_username_key7 UNIQUE (username),
    CONSTRAINT authentication_username_key8 UNIQUE (username),
    CONSTRAINT authentication_username_key9 UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.authentication
    OWNER to postgres;


-- Table: public.farms
CREATE TABLE IF NOT EXISTS public.farms
(
    farm_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    region text COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    crops text COLLATE pg_catalog."default",
    hectares bigint,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    carbon_sequestered bigint,
    CONSTRAINT farms_pkey PRIMARY KEY (farm_id)
)

TABLESPACE pg_default;

-- Table: public.farmers
CREATE TABLE IF NOT EXISTS public.farmers
(
    farmer_id   SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    products    TEXT,
    status      VARCHAR(255) DEFAULT 'Unverified',
    address     VARCHAR(255),
    email       VARCHAR(255),
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT farmers_status_check 
        CHECK (status IN ('Verified', 'Unverified'))
);

ALTER TABLE IF EXISTS public.farmers
    OWNER TO postgres;


-- Table: public.vendors
CREATE TABLE IF NOT EXISTS public.vendors
(
    vendor_id   SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,

    -- NEW: Proper FK instead of plain text
    category_id INT REFERENCES public.vendor_categories(cat_id) ON DELETE SET NULL,

    address     VARCHAR(255),
    phone       VARCHAR(255) NOT NULL,
    email       VARCHAR(255),

    status      VARCHAR(255) DEFAULT 'Unverified',

    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT vendors_status_check 
        CHECK (status IN ('Verified', 'Unverified'))
);

ALTER TABLE IF EXISTS public.vendors
    OWNER TO postgres;

-- Table: public.vendor_categories
CREATE TABLE IF NOT EXISTS public.vendor_categories
(
    cat_id      SERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE IF EXISTS public.vendor_categories
    OWNER TO postgres;

-- Create table: public.cooperatives
CREATE TABLE IF NOT EXISTS public.cooperatives
(
    coop_id            SERIAL PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    registration_no    VARCHAR(100) UNIQUE,
    status             VARCHAR(50) DEFAULT 'Active',     -- Active | Inactive | Suspended
    address            VARCHAR(255),
    region             VARCHAR(100),
    contact_person     VARCHAR(150),
    phone              VARCHAR(50),
    email              VARCHAR(255),
    members_count      INTEGER DEFAULT 0,
    established_at     DATE,
    created_at         TIMESTAMPTZ DEFAULT NOW(),
    updated_at         TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT cooperatives_status_check CHECK (status IN ('Active','Inactive','Suspended'))
);

ALTER TABLE IF EXISTS public.cooperatives
    OWNER TO postgres;

-- Table: public.soil_assessment
CREATE TABLE IF NOT EXISTS public.soil_assessment
(
    assessment_id SERIAL PRIMARY KEY,

    farm_id INTEGER NOT NULL,
    assessment_date DATE NOT NULL DEFAULT CURRENT_DATE,

    -- Soil Condition Values
    ph_level NUMERIC(4,2),                 -- Example: 6.50
    nitrogen NUMERIC(10,2),                -- N (kg/ha)
    phosphorus NUMERIC(10,2),              -- P (kg/ha)
    potassium NUMERIC(10,2),               -- K (kg/ha)

    organic_matter NUMERIC(5,2),           -- percent %
    moisture_level NUMERIC(5,2),           -- percent %
    soil_texture VARCHAR(255),             -- e.g., Clay, Loam, Sandy Loam, etc.

    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT soil_assessment_farm_fk 
        FOREIGN KEY (farm_id) REFERENCES public."Farms"(farm_id)
        ON DELETE CASCADE
);

-- Table: public.suppliers
CREATE TABLE public.suppliers (
    supplier_id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    contact_person TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    category TEXT, -- e.g., seeds, fertilizers, feeds, equipment
    rating NUMERIC(3,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- order tables
-- Table: public.purchase_orders & public.sales_orders
CREATE OR REPLACE FUNCTION generate_po_id()
RETURNS VARCHAR AS $$
DECLARE
    chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    result TEXT := '';
    i INT;
BEGIN
    FOR i IN 1..6 LOOP
        result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE purchase_orders (
    po_id VARCHAR(6) PRIMARY KEY DEFAULT generate_po_id(),

    farm_id INTEGER NOT NULL,
    details TEXT,

    status VARCHAR(20) NOT NULL CHECK (
        status IN ('advised', 'draft', 'submitted')
    ),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_po_farm
        FOREIGN KEY (farm_id)
        REFERENCES farms(farm_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_po_coop
        FOREIGN KEY (coop_id)
        REFERENCES cooperatives(coop_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);



CREATE TABLE public.sales_orders (
    so_id BIGSERIAL PRIMARY KEY,
    coop_id BIGINT,
    farm_id BIGINT,
    vendor_id BIGINT NOT NULL,

    items JSONB NOT NULL,       -- harvested products sold
    total_amount NUMERIC(10,2) DEFAULT 0.00,

    status TEXT DEFAULT 'Pending',
    -- Pending, Confirmed, Packed, Out for Delivery, Completed, Cancelled

    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_vendor
        FOREIGN KEY (vendor_id)
        REFERENCES public.vendors(vendor_id)
        ON DELETE SET NULL
);


-- Trigger: on new soil_assessment, create purchase orde
-- 1. Create Function
CREATE OR REPLACE FUNCTION create_po_from_soil_assessment()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.purchase_orders (
        coop_id,
        farm_id,
        ordered_by,
        items,
        total_amount,
        status
    )
    VALUES (
        NULL,
        NEW.farm_id,
        'System (Soil Assessment)',
        jsonb_build_object(
            'source', 'soil_assessment',
            'assessment_id', NEW.assessment_id,
            'recommended_items', jsonb_build_array()
        ),
        0.00,
        'Pending'
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Create Trigger
CREATE TRIGGER trg_create_po_after_soil_assessment
AFTER INSERT ON public.soil_assessment
FOR EACH ROW
EXECUTE FUNCTION create_po_from_soil_assessment();
